plugins {
    id 'org.openjfx.javafxplugin' version '0.0.14'
}

ecco.adapter = true

javafx {
    version = "17"
    modules = ['javafx.base', 'javafx.controls', 'javafx.graphics', 'javafx.swing']
}
dependencies {
	 // https://mvnrepository.com/artifact/org.eclipse.jdt/org.eclipse.jdt.core
    implementation 'org.eclipse.jdt:org.eclipse.jdt.core:3.36.0' // group: 'org.eclipse.jdt', name: 'org.eclipse.jdt.core', version: '3.36.0'

    implementation project(':ecco-service')
}
